apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: nodejs
  name: kuldeeps-cicd-pipeline
spec:
  workspaces:
    - name: kuldeeps-workspace
      description: |
        This workspace stores the cloned repository and is available to all steps
  params:
    - name: image-repo
      type: string
      description: Docker image name
      default: quay.io/kuldeeps_ibm/next-app
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: https://github.com/cloud-native-garage-method-cohort/kuldeeps-rachelc-assignment-repo/tree/main/apac-bootcamp-cicd
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: kuldeeps-workspace
    - name: build-image
      runAfter:
        - clone-repository
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: kuldeeps-workspace
    - name: kustomize-build
      runAfter:
        - build-image
      params:
        - name: image-with-tag
          value: "quay.io/kuldeeps_ibm/next-app=$(params.image-repo):$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: Task
        name: kustomize-build
      workspaces:
        - name: source
          workspace: kuldeeps-workspace
    - name: test-deploy
      runAfter:
        - kustomize-build
      params:
        - name: app-namespace
          value: kuldeep-singh-pipeline-from-scratch
        - name: app-name
          value: kuldeep-singh-pipeline-from-scratch
      taskRef:
        kind: Task
        name: test-deploy
      workspaces:
        - name: source
          workspace: kuldeeps-workspace

    